### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by nitz**
I figure as you're going to be getting a heap more attention here as the campaign goes on, makes sense to have the readme updated with the latest specs! (I also linked to the campaign in the readme.)

### CODE REVIEW

**Comment by gregdavill** [comment]
I'll take a look over these tomorrow, thanks.

I was planning a deep clean of this repo, probably tag and then remove the older designs.

**Comment by nitz** [comment]
For sure, feel free to use whichever bits are useful, or chuck 'em all if a clean slate is in order 🙂

**Comment by tommythorn** [comment]
2x Stardard [SYZYGY compatible connectors](https://syzygyfpga.io/)

should probably "Standard"

  2 × Standard ...

even better :)

**Comment by gregdavill** [comment]
Doh. Why can't the GitHub review panel have a spell checker built in. -_-

**Comment by nitz** [comment]
Or why can't the dummy who did the typing in the first place turn the spell checker on in their editor 🙃

**Comment by gregdavill** [comment]
Fixed in: 9eb4c4e246c7168311855992b435f46eb16c4384

**Pull request merged**
